
DROP DATABASE DB1;
CREATE DATABASE DB1
USE DB1;
GO

DROP TABLE PHIEUVANCHUYENHANHLY;
CREATE TABLE PHIEUVANCHUYENHANHLY(
	MAPHIEUVANCHUYEN VARCHAR(5) PRIMARY KEY,
	MAPHONG VARCHAR(5),
	SOLUONGHANHLY INT,
	MAPHIEUDATPHONG VARCHAR(5)
);

DROP TABLE DANHSACHKHCHODAT;
CREATE TABLE DANHSACHKHCHODAT(
	MAKH VARCHAR(5),
	TENKH VARCHAR(50)
);

DROP TABLE NHANVIEN;
CREATE TABLE NHANVIEN(
	MANV VARCHAR(5) PRIMARY KEY,
	TENNV VARCHAR(50),
	SDT VARCHAR(10),
	NGAYTHUE DATE,
	VAITRO VARCHAR
);

CREATE TABLE NVBELLMAN(
	MANV VARCHAR(5),
	CATRUC VARCHAR(5), --NGAY, DEM
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE NVBUONGPHONG(
	MANV VARCHAR(5),
	KHUVUCQL VARCHAR(5), --TANG1, TANG2
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE NVKETOAN(
	MANV VARCHAR(5),
	SLHOSOTHANHTOAN INT,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE NVLETAN(
	MANV VARCHAR(5),
	VITRI VARCHAR(5), --BAN1, BAN2
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

